version: '3'

volumes:
  postgres_data_test: {}

services:
  fastapi_test: &core
    build:
      context: .
      dockerfile: ./deploy/compose/local/fastapi.dockerfile
    depends_on:
      - postgres_test
      - db-init_test
    command: pytest -vvv --cov=app --cov-branch --cov-report term-missing --cov-report xml --cov-report html --junit-xml=report.xml --cov-fail-under=80
    env_file:
      - .env.test
    restart: "no"

  db-init_test:
    <<: *core
    depends_on:
      - postgres_test
    ports: []
    env_file:
      - .env.test
    restart: "no"
    command: /start-db-init.sh

  postgres_test:
    image: postgres:13
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env.test
    restart: "unless-stopped"
    ports:
      - "5432:5432"
