version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: ./deploy/compose/develop/nextjs.dockerfile
    networks:
      - app-network

  nginx:
    build: ./deploy/compose/common
    ports:
      - 80:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
