"""empty message

Revision ID: 0ae162453c4c
Revises: 72513d21af07
Create Date: 2024-06-26 15:36:25.849707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae162453c4c'
down_revision: Union[str, None] = '72513d21af07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_firstname_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_firstname_key', 'user', ['firstname'])
    # ### end Alembic commands ###
