"""empty message

Revision ID: 72513d21af07
Revises: 555f91f0ecbd
Create Date: 2024-06-26 15:17:39.065091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72513d21af07'
down_revision: Union[str, None] = '555f91f0ecbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(), nullable=True))
    op.add_column('user', sa.Column('qualification', sa.String(), nullable=True))
    op.add_column('user', sa.Column('post', sa.String(), nullable=True))
    op.add_column('user', sa.Column('description', sa.String(), nullable=True))
    op.add_column('user', sa.Column('years', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('link_to_vk', sa.String(), nullable=True))
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['firstname'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.drop_column('user', 'link_to_vk')
    op.drop_column('user', 'years')
    op.drop_column('user', 'description')
    op.drop_column('user', 'post')
    op.drop_column('user', 'qualification')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
